### ISSUE TITLE
rust-analyzer: Unresolved macro call for dotenv!

### ISSUE THREAD

**Issue by allan2** [allan2/dotenvy#1]
This is the same issue as [rust-analyzer #9606](https://github.com/rust-analyzer/rust-analyzer/issues/9606).

When using rust-analyzer with `dotenv!`, this mesage appears:
```
unresolved macro `dotenv!`rust-analyzerunresolved-macro-call
```

Example repo: https://github.com/allan2/dotenv-macro

_src/main.rs_:
```rust
use dotenvy_codegen::dotenv;

fn main() {
    println!("{}", dotenv!("MSG"));
}
```

The issue appears to be related to `proc-macro-hack`  according to [this comment](https://github.com/rust-analyzer/rust-analyzer/issues/9606#issuecomment-919240134).

**Comment by kdwarn** [comment]
Is this still an issue with newer versions of rust-analyzer? I'm not getting that message in either Neovim or Helix, with rust-analyzer 1.65.

**Comment by sonro** [comment]
I haven't seen this myself. Either way, `proc_macro_hack` can be removed: see #43.
