### ISSUE TITLE
Opening .env files from stdin (or process substitution)

### ISSUE THREAD

**Issue by gvangool** [allan2/dotenvy#115]
I have 2 `.env` files that I want to load.

```bash
echo PORT=8000 > .env.defaults
echo PASSWORD=my-very-secret-password > .env.local
```

I'm trying to load this as 1 new file:
- as `-` for stdin
```bash
cat .env.defaults .env.local | dotenvy -f - list
# error: failed to load environment: path not found
```
- or using process substitution
```bash
dotenvy -f <(cat .env.defaults .env.local) list
# error: failed to load environment: path not found
```

Could one of these options be supported? Or an alternative that achieves a similar thing?

**Comment by allan2** [comment]
I just updated the CLI to take a path instead of a filename.


You can use a temp file now:
```
echo "FOO=bar" > /tmp/tmpenv && dotenvy -f /tmp/tmpenv printenv FOO
```

Will that work for you?

**Comment by allan2** [comment]
Closing as the temp file should work for this. Feel free to reopen if your issue is not resolved.
