### ISSUE TITLE
Bump minor version for next release

### ISSUE THREAD

**Issue by allan2** [allan2/dotenvy#13]
`from_read` was added in 0.15.2.

The minor version should have been incremented instead of the patch version, i.e. 0.15.2 should have been 0.16.

Thanks @mkmik https://github.com/influxdata/influxdb_iox/pull/5461

**Comment by Dylan-DPC** [comment]
Thanks. 
Semver works differently in pre 1.0 range: 
0.x is often considered the major while the next (0.*.y) is often considered the minor release

new features can be added in patch versions as long as no breaking change is involved

if you are dependent on a certain version of a dependency you need to depend on that version and higher

**Comment by mkmik** [comment]
TIL thanks

**Comment by allan2** [comment]
@Dylan-DPC, thanks for clarifying.

Closing
