### ISSUE TITLE
"No `EnvLoader` in the root" when trying to compile example code outside crate

### ISSUE THREAD

**Issue by quintuple-lained** [allan2/dotenvy#137]
Hello, i am running into the issue that whenever i try to use dotenvy in a project or when trying to run one of the provided examples in a stand-alone way:

```
error[E0432]: unresolved imports `dotenvy::EnvLoader`, `dotenvy::EnvSequence`
 --> src/main.rs:7:15
  |
7 | use dotenvy::{EnvLoader, EnvSequence};
  |               ^^^^^^^^^  ^^^^^^^^^^^ no `EnvSequence` in the root
  |               |
  |               no `EnvLoader` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `testing` (bin "testing") due to 1 previous error
```

Steps to reproduce the issue:
1. create a new project using `cargo init <name>`
2. add `dotenvy = "0.15.7"` to Cargo.toml
3. copy the code from the dev-prod example main.rs into the new project main.rs
4. run `cargo run`

this has happened on the following systems using the following rust versions:
wsl gentoo rust-bin 1.80.1
vm gentoo rust-bin 1.80.1
wsl debian rust 1.76

**Comment by allan2** [comment]
`EnvLoader` wil be in the 0.16 release which is not out yet. For the current API, you can check docs.rs and the crates.io README.

**Comment by quintuple-lained** [comment]
I'm sorry for the misunderstanding, thank you for referring me to the correct sources

**Comment by andywwright** [comment]
> `EnvLoader` wil be in the 0.16 release which is not out yet

Well, then it probably shouldn't be on the main page. I wonder how many thousands have stumbled upon that.

**Comment by quintuple-lained** [comment]
> Well, then it probably shouldn't be on the main page.

"Talk is cheap, send patches" as someone from the ffmpeg team put it once
