### ISSUE TITLE
Minimum Supported Rust Version?

### ISSUE THREAD

**Issue by rillian** [allan2/dotenvy#20]
Thanks for taking over maintaining dotenvy! It was great to have an alternative when `cargo audit` started warning about the old crate being unmaintained.

Unfortunately today's 0.15.4 release broke our application, which is building on rust 1.58.1. I see you're only testing on stable, beta, and nightly; would you consider supporting older toolchains as well?

Many crates declare a minimum supported rust version (MSRV) so downstream users have some guidance toward the impact on their support surface.

**Comment by allan2** [comment]
You read my mind!

Thanks for the PR. v0.15.5 published
