### ISSUE TITLE
GitHub Actions for linting and formatting

### ISSUE THREAD

**Issue by allan2** [allan2/dotenvy#30]
It would be nice if we had this.

PRs are very welcome.

**Comment by sonro** [comment]
I can't see any runs on the [actions tab](https://github.com/allan2/dotenvy/actions/workflows/rust.yml).  In particular it seems the PR action is not working.

They seem to work on my [fork](https://github.com/sonro/dotenvy/actions/workflows/rust.yml) for pushes. I did have to enable a [setting](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/).

I think it would be good to make sure they are running before they are updated.

**Comment by allan2** [comment]
Thanks @sonro. I enabled them just now.

**Comment by allan2** [comment]
Closed by #31
