### ISSUE TITLE
Should we update MSRV policy

### ISSUE THREAD

**Issue by sonro** [allan2/dotenvy#33]
With a few tweaks* we can support Rust version 1.42.0 (September 2020). 

But should we?

Ensuring support for Rust released 2 years ago seems sensible for a library primarily used in dev environments.

---

*Changes:

- `println!` macros in [docs](https://github.com/allan2/dotenvy/blob/a405018eb368b8ec92605157f40e4dc7c8d756ba/dotenv/src/lib.rs#L35)
- `println!` in 1 [example](https://github.com/allan2/dotenvy/blob/a405018eb368b8ec92605157f40e4dc7c8d756ba/dotenv/examples/list_variables.rs#L7)

The examples certainly need updating anyway.

**Comment by allan2** [comment]
Sure! Let's kick out the format strings.

**Comment by Dylan-DPC** [comment]
While at it, I'd rather push MSRV more aggressively, maybe to 1.56.1 at least so we can specify the rust version in Cargo.toml and maybe look through the codebase and see if we can add any other features that were introduced

**Comment by sonro** [comment]
Yes, maybe 2 years is a bit too conservative. 1.56.1 is 1 year ago (n-8). After going down the rabbit hole([1] [2]) of other crate's policies n-8 seems like a good compromise. 

[1]: https://github.com/rust-lang/libs-team/issues/72
[2]: https://github.com/matklad/once_cell/blob/04e1d59ce7d0d8f2d73c12e84919b927c37bc9e7/src/lib.rs#L272
