### ISSUE TITLE
Change misleading usage examples

### ISSUE THREAD

**Issue by xiaoas** [allan2/dotenvy#37]
The example in README use `dotenvy::dotenv` feels miss-leading:
```rust
fn main() {
    dotenv().ok();

    for (key, value) in env::vars() {
        println!("{key}: {value}");
    }
}
```
calling `.ok` on dotenv(), a `Result`, turns it into a `Option`. This is not what most people might expect imo. Changing to some error handling might better serve the intention:
```rust
fn main() -> Result<(), dotenvy::Error>{
    dotenv()?; // or dotenv().unwrap();

    for (key, value) in env::vars() {
        println!("{key}: {value}");
    }
}
```

**Comment by sonro** [comment]
The reason for the `.ok()` is to ignore the error.

The `.env` file that this loads might not be avaiable on the deployed version of your app. The environment variables would usually be set elsewhere. By using this pattern no error is thrown if the file isn't found.

As some users may **require** a `.env` file, they have the option of using its result type.

---

You are right there needs to be better documentation around this issue, it certainly doesn't feel very "rusty" to just `.ok()` an error like that.

**Comment by allan2** [comment]
@xiaoas, thanks for reporting. It's been brought up a few times already that `.ok()` is not ideal.

I've replaced some `.ok()`s in the docs with `.unwrap()` but there are still a few instances left, including the README example.
Feel free to open a PR.
