### ISSUE TITLE
Remove proc_macro_hack

### ISSUE THREAD

**Issue by sonro** [allan2/dotenvy#43]
The [proc_macro_hack crate](https://crates.io/crates/proc-macro-hack) is no longer needed since [rustc 1.45.0](https://github.com/rust-lang/rust/releases/tag/1.45.0). As this library doesn't support compiler versions before 1.56.1, the dependency should be removed and replaced with the [native version](https://doc.rust-lang.org/reference/procedural-macros.html#function-like-procedural-macros).

This would fix the rust analyzer errors highlighted in #1, remove an unnecessary dependency, and combine the `dotenvy_macro` and `dotenvy_codegen_impl` crates.

**Comment by allan2** [comment]
Thank you!

I've moved the legacy code to [allan2/dotenvy-codegen-impl](https://github.com/allan2/dotenvy-codegen-impl). just adding a deprecation notice. Let me know if anything should be changed before I publish a release.
