### ISSUE TITLE
`Iter` type being leaked publicly

### ISSUE THREAD

**Issue by sonro** [allan2/dotenvy#48]
The public functions [`dotenv_iter`], [`from_read_iter`], [`from_filename_iter`], and [`from_path_iter`] all return the [`Iter`] struct - which is currently not public. It needs to be so users have easier to access its documentation.

As a public type it needs to eagerly implement common traits ([Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#types-eagerly-implement-common-traits-c-common-traits)) and have decent documentation.

Its naming could also be improved. It is clear enough in the context of a library internal, but when constructed and viewed externally [`Iter`] is fairly nebulous. Are there any renaming suggestions?

Making [`Iter`] public would also make [`from_read_iter`] obsolete as all it does is call `Iter::new`. 

[`Iter`]: https://github.com/allan2/dotenvy/blob/0afdc926d5fe80c1f61ff4eef9ed05f01c9c956b/dotenv/src/iter.rs#L9
[`dotenv_iter`]: https://github.com/allan2/dotenvy/blob/0afdc926d5fe80c1f61ff4eef9ed05f01c9c956b/dotenv/src/lib.rs#L207
[`from_read_iter`]: https://github.com/allan2/dotenvy/blob/0afdc926d5fe80c1f61ff4eef9ed05f01c9c956b/dotenv/src/lib.rs#L166
[`from_filename_iter`]: https://github.com/allan2/dotenvy/blob/0afdc926d5fe80c1f61ff4eef9ed05f01c9c956b/dotenv/src/lib.rs#L123
[`from_path_iter`]: https://github.com/allan2/dotenvy/blob/0afdc926d5fe80c1f61ff4eef9ed05f01c9c956b/dotenv/src/lib.rs#L90

**Comment by LeoniePhiline** [comment]
Naming: `Iter` is fine, since it is namespaced by the crate. See also https://docs.rs/error-chain/latest/error_chain/struct.Iter.html

**Comment by LeoniePhiline** [comment]
So `pub use iter::Iter` in the root namespace?

**Comment by sonro** [comment]
I am leaving this issue unresolved until the documentation for the type has been written. Thank you @LeoniePhiline for the starter PR.

**Comment by allan2** [comment]
On the [v0.16 branch](https://github.com/allan2/dotenvy/blob/v0.16/dotenvy/src/iter.rs), I have made `Iter` private.
The `*_iter` functions are now deprecated. `EnvLoader::load` returns `HashMap`.

Does anyone object to `Iter` being private?
