### ISSUE TITLE
Documentation does not explain difference between `from_filename` and `from_path`

### ISSUE THREAD

**Issue by LeoniePhiline** [allan2/dotenvy#53]
... which is the recursive search up the file tree for a matching filename.

**Comment by LeoniePhiline** [comment]
Note: CI in #54 fails, but not due to the PR content. Looks like an `actions-rs/tarpaulin` issue.

**Comment by allan2** [comment]
At first glance, I was confused also confused by `from_filename` and `from_path`. In addition to docs, this could benefit from renaming (#101).

**Comment by allan2** [comment]
`from_filename` is now deprecated. This was to prevent directory traversal attacks.

There is a [find example](https://github.com/allan2/dotenvy/blob/v0.16/examples/find/src/main.rs) for those who wish to search for the matching filename up the tree.
