### ISSUE TITLE
LICENSE files are missing from the published crates

### ISSUE THREAD

**Issue by alebastr** [allan2/dotenvy#61]
Hello,

It appears that the releases of dotenvy on crates.io do not include a license file. The MIT license requires all copies of the source code to include the text of the license:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

It would be appreciated if you could address that either by copying or by linking `LICENSE` into each crate in one of the following releases.

Thanks in advance!

**Comment by allan2** [comment]
Thanks for pointing this out. Would you like to make a PR?
