### ISSUE TITLE
How do you make a test that doesn't fail if `dotenv()` doesn't find the `.env` file?

### ISSUE THREAD

**Issue by valentinegb** [allan2/dotenvy#62]
In my Rust program, I have a `.env` file for my environmental variables when I run the tests on my computer. However, I also run the tests via a GitHub workflow, where I have a repository secret defined. Currently, these tests all fail in the workflow because there is no `.env` file present. How should I resolve this?

**Comment by valentinegb** [comment]
Right now I'm just doing this:
```rs
#![allow(unused_must_use)]
dotenv();
```
But I'd rather not have to disable any warnings.

**Comment by allan2** [comment]
`dotenv()` returns `Result`. You can handle the error or [ignore it](https://doc.rust-lang.org/std/result/enum.Result.html#method.ok).


```rust
dotenv().ok(); // discards the error if there is one
```

**Comment by valentinegb** [comment]
Oh- yeah, duh, thanks lol
