### ISSUE TITLE
Named pipes aren't supported out of the box

### ISSUE THREAD

**Issue by ChristianIvicevic** [allan2/dotenvy#65]
I am using Doppler to handle secrets and I am running `doppler run --mount .env --command "while true; do sleep 1; done"` which creates `.env` as a named pipe. `dotenvy` fails to parse anything from that file so I had to add the following as a workaround:
```rust
match File::open(".env") {
    Ok(file) => {
        dotenvy::from_read(file).ok();
    }
    Err(_) => {
        tracing::debug!("No .env file found");
    }
}
```
I wanted to ask whether you can look into supporting named pipes natively instead.

**Comment by allan2** [comment]
Can you find an example .env file?

**Comment by allan2** [comment]
Hi @ChristianIvicevic, is this still an issue?
