### ISSUE TITLE
About MSRV and the `cli` feature

### ISSUE THREAD

**Issue by CosmicHorrorDev** [allan2/dotenvy#71]
I'd like to open a PR to update the `clap` version to v4, but `clap` normally maintains a very aggressive MSRV compared to this crate's current MSRV. Do you think it would be appropriate to use a higher MSRV for the `cli` feature to keep up to date with `clap` updates while maintaining a more tame MSRV when not using the `cli` feature?

**Comment by Dylan-DPC** [comment]
Thanks for opening the issue. I'd rather have a single MSRV for the entire repo instead having a feature have a different one because it becomes trickier to handle and can be a footgun.
