### ISSUE TITLE
Add from_filename_override variant to dotenvy_macro

### ISSUE THREAD

**Issue by nirvdrum** [allan2/dotenvy#72]
I may be going about this wrong, but I'm working on a Yew application with some configuration values that need to change based on environment (e.g., GraphQL server URLs). While Rust doesn't have the notion of an "environment" in the same way that JavaScript does, using `from_filename` I can approximate that and keep the config neatly split into multiple files. However, because this is WebAssembly, I need the values to be read in during compilation. _dotenv\_macro_ only supports reading in a file named _.env_ via the `dotenv!` macro. It'd be quite helpful if there were a corresponding `from_filename` or `from_filename_override!` macro.

**Comment by allan2** [comment]
More configurable compile-time loading is coming.

This issue is replaced by #128.
