### ISSUE TITLE
dotenvy_macro could use a option_env!() macro

### ISSUE THREAD

**Issue by wfraser** [allan2/dotenvy#85]
like the one in std: https://doc.rust-lang.org/std/macro.option_env.html

If the var isn't there, it returns None, instead of raising a compile error. There doesn't seem to be a way to do this with dotenvy currently.

**Comment by allan2** [comment]
Good idea! PRs are welcome.

**Comment by allan2** [comment]
Due to new configs, many macros would be required to cover the config space. Superseded by #128
