### ISSUE TITLE
dotenvy silently fails to parse strings with dollar signs

### ISSUE THREAD

**Issue by MakeShiftArtist** [allan2/dotenvy#93]
I ran into this issue when storing a password in a .env file and not understanding why I couldn't authenticate. After some testing, I was able to figure out that the Dollar Sign <kbd>$</kbd> was causing the string parser from `dotenvy::var("KEY_NAME")` to fail.

# Minimum Reproduceable Example
```rs
// main.rs
use dotenvy::dotenv;

fn main() {
    dotenv()
        .and_then(|_| {
            println!("{}", dotenvy::var("NO_DOLLARS").expect("NO_DOLLARS failed"));
            println!("{}", dotenvy::var("DOLLARS").expect("DOLLARS failed"));

            Ok(())
        })
        .unwrap();
}
```
Store variables in .env file
```env
NO_DOLLARS="Hello%World^&FooBar*()_+"
DOLLARS="H$ello$%World^$&FooBar*()_$+"
```

As you can see, the `DOLLARS` variable includes random dollar signs throughout. However, if you run this script the strings returned do not match what's saved in the `.env` file

```sh
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target\debug\foobar.exe`
Hello%World^&FooBar*()_+
H%World^&FooBar*()_+
```

**Comment by MakeShiftArtist** [comment]
This issue can be closed. After further digging, I believe this is actually intended behavior, as `$foobar$` is used to indicate evaluating the value of `foobar`.

**Comment by allan2** [comment]
I'm glad you worked it out!

**Comment by HookedBehemoth** [comment]
Could you perhaps document this behavior? Besides this issue there is nothing pointing this behavior out and having an unescaped dollar will silently fail.
The dotenv repository has this in the readme.
